version: "3.8"
services:
  mysql:
    image: mysql:latest
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: timetable
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser1234
      MYSQL_ROOT_PASSWORD: dbuser1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data
  filesharing:
    depends_on:
      - mysql
      - redis
    ports:
      - 3000:3000
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
volumes:
  db_data:
  redis_data: