version: "3.8"
services:
  mysql:
    image: mysql:latest
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: timetable~~
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser1234
      MYSQL_ROOT_PASSWORD: dbuser1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    db_data: